# -*- coding: utf-8 -*-
"""IABD_M02_T02_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvJFKqP-gXgmrB95G2607vWWOEjuvQsN

Tienes el siguiente conjunto de 5 puntos: (1,2), (2,3), (3,4), (4,5) y (10,10), aplica paso por paso el algoritmo Isolation Forest para encontrar el outlier.
El algoritmo Isolation Forest calcula un gran número de árboles de decisión con valores aleatorios. Para este ejemplo concreto, crea estratégicamente 4 árboles aleatorios para que el outlier (es decir, el punto (10,10)) sea detectado.
"""

import numpy as np
from sklearn.ensemble import IsolationForest

# Definir el conjunto de datos
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [10, 10]])

# Configurar el modelo de Isolation Forest
# Usaremos como estimadores 4, para crear los 4 árboles que pide el ejercicio
isolation_forest = IsolationForest(n_estimators=4, random_state=42)

# Entrenar el modelo
isolation_forest.fit(X)

# Predecir outliers
# La función predict devuelve -1 para outliers y 1 para puntos normales
predictions = isolation_forest.predict(X)

predictions

"""El resultado, ([ 1, 1, 1, 1, -1]), efectivamente idenfica el punto (10,10) como outlier"""