# -*- coding: utf-8 -*-
"""IABD_MP2_T03_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuX-EIRvAdFiv1VO0PfGvLrTXl56kKVt

Tenemos el siguiente conjunto de 4 datos: (3, 7), (5, 2), (8, 9),y (4, 6).
Aplica paso a paso los algoritmos de Min-max Scaling y Z-score para normalizarlos (comprueba que, en este último caso, la media de los resultados es 0 y la desviación estándar es 1).
La idea de este ejercicio es comparar cómo se hace este proceso a mano con cómo se realiza en Python. Aquí está solamente la parte programada.
"""

import numpy as np

data = np.array([[3, 7], [5, 2], [8, 9], [4, 6]])

# Min-Max Scaling
min_vals = data.min(axis=0)
max_vals = data.max(axis=0)
min_max_scaled = (data - min_vals) / (max_vals - min_vals)

# Z-score Normalization
mean_vals = data.mean(axis=0)
std_vals = data.std(axis=0)
z_score_scaled = (data - mean_vals) / std_vals

# Comprobación de la media y desviación estándar para Z-score
z_mean = z_score_scaled.mean(axis=0)
z_std = z_score_scaled.std(axis=0)

# Imprimir resultados
print("Min-Max Scaling:\n", min_max_scaled)
print("\nZ-score Normalization:\n", z_score_scaled)
print("\nComprobación de la media (debe ser 0):\n", z_mean)
print("Comprobación de la desviación estándar (debe ser 1):\n", z_std)