# -*- coding: utf-8 -*-
"""IABD_MP2_T03_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yTXEfiIlqbO8FvwF4mWbFCiajpbzUbg1

EJERCICIO 3: Tienes un conjunto de datos sobre los futbolistas de un equipo de fútbol en que aparecen diferentes estadísticas numéricas avanzadas y una única variable categórica "Posición", con cuatro valores: Portero, Defensa, Centrocampista y Delantero.
Aplica las técnicas de Label Encoding y One-hot encoding y muestra los datos resultado si tienes los siguientes datos de entrada para 5 jugadores: (0.4, 1.6, 1.2, Portero), (1, 1.1, 1.5, Defensa), (0.2, 0.6, 1, Defensa), (2, 1.9, 1.7, Centrocampista), (1, 0.5, 2, Delantero).
La idea de este ejercicio es comparar cómo se hace este proceso a mano con cómo se realiza en Python. Aquí está solamente la parte programada.
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder


data = [[0.4, 1.6, 1.2, 'Portero'],
        [1, 1.1, 1.5, 'Defensa'],
        [0.2, 0.6, 1, 'Defensa'],
        [2, 1.9, 1.7, 'Centrocampista'],
        [1, 0.5, 2, 'Delantero']]

# Crear DataFrame original
df = pd.DataFrame(data, columns=['Stat1', 'Stat2', 'Stat3', 'Posicion'])

# Asignar un valor numérico único a cada posición: Portero (0), Defensa (1), Centrocampista (2) y Delantero (3).
df_label_encoding = df.copy() #Crea un nuevo df para guardar los tres
le = LabelEncoder()
df_label_encoding['Posicion_encoded'] = le.fit_transform(df['Posicion'])

# Crear nuevas columnas para cada posición, con un valor de 1 si el jugador ocupa esa posición y 0 en caso contrario.
df_one_hot_encoding = df.copy()
encoded_columns = pd.get_dummies(df['Posicion'], prefix='Posicion')
df_one_hot_encoding = df_one_hot_encoding.join(encoded_columns)

# Mostrar los tres dataset para ver la diferencia
print("Dataset original:")
print(df[['Stat1', 'Stat2', 'Stat3', 'Posicion']])
print("\nDataFrame con Label Encoding:")
print(df_label_encoding)
print("\nDataFrame con One-hot Encoding:")
print(df_one_hot_encoding)