# -*- coding: utf-8 -*-
"""IABD_M04_ACT_01_05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jnzupQVu2AfVLbburPg9g77Jq0kRbhN
"""

Utiliza las bibliotecas requests y BeautifulSoup para realizar web scraping de la página
 principal de "http://books.toscrape.com/".
Extrae el título y el precio de cada libro listado en la página.

"""Primero, instalar la biblioteca requests y BeautifulSoup"""

!pip install requests beautifulsoup4

"""Importar las bibliotecas:
bs4 para el scap, y prettytable para presentar los resultado
"""

import requests
from bs4 import BeautifulSoup
from prettytable import PrettyTable

"""Hacer la request a la página, y comprobar que la petición fue exitosa.
Si lo es, parsear el contenido.
Buscar todos los libros en la página, y sobre cada uno de ellos buscar la información que se busca. En este caso,
titulo y precio.
Las etiquetas se encuentran inspeccionando los elementos en la página web en el navegador.
Por último, mostrar en pantalla la información en una tabla
"""

# URL de la página que vamos a scrapear
url = "http://books.toscrape.com/"

# Hacer una petición GET a la página
response = requests.get(url)

# Comprobar que la petición fue exitosa
if response.status_code == 200:
    # Asegurarse de que el contenido está en UTF-8. Si no, aparecen símbolos
    response.encoding = 'utf-8'

    # Crear un objeto BeautifulSoup y parsear el contenido HTML
    soup = BeautifulSoup(response.text, 'html.parser')

    # Crear una tabla
    table = PrettyTable()
    table.field_names = ["Título", "Precio"]  # Nombres de las columnas

    # Alinear las columnas
    table.align["Título"] = "l"  # Alinear a la izquierda
    table.align["Precio"] = "r"   # Alinear a la derecha

    # Encontrar todos los libros en la página
    books = soup.find_all('article', class_='product_pod')

    # Iterar sobre cada libro y extraer la información deseada
    for book in books:
        title = book.h3.a['title']  # Título del libro
        price = book.find('p', class_='price_color').text  # Precio del libro

        # Agregar fila a la tabla
        table.add_row([title, price])


    # Imprimir la tabla
    print(table)
else:
    print(f'Error al acceder a la página: {response.status_code}')