# -*- coding: utf-8 -*-
"""IABD_MP4_T03_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z3FFfIoi9hp-FhX4DWVMHsRjEHi3T1lZ

EJERCICIO 3: Análisis del Dataset Iris:
1.	Carga el dataset Iris:
Al ser un dataset muy utilizado, se podría cargar directamente con la librería sklearn:
from sklearn.datasets import load_iris

iris = load_iris()

pero voy a cargarlo  del csv, como si fuese un dataset que no es público y cargarlo con pandas.read_csv().
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

ruta_archivo = 'Iris.csv'
iris_df = pd.read_csv(ruta_archivo)

print(iris_df.head()) # Muestra las primeras filas del DataFrame, para asegurar que lo ha cargado

"""2.	Histograma multivariable: Crea un histograma que muestre la distribución de cada una de las cuatro características (sepal_length, sepal_width, petal_length, petal_width) para cada especie.

La forma más sencilla de crear un histograma bonito es usar la libreria seaborn. La importo en la cabecera del programa para poder usarla.

Uso dislpot() para crear un histograma para cada una de las caracterísictas, separando las especies. Para que tengan un nombre coherente y sea más fácil de leer, creo un diccionario de nombres.


"""

# Lista de caracteristicas
features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

# Diccionario para mapear nombres de columnas a nombres legibles
nombres_legibles = {
    'SepalLengthCm': 'Longitud del sépalo (cm)',
    'SepalWidthCm': 'Ancho del sépalo (cm)',
    'PetalLengthCm': 'Longitud del pétalo (cm)',
    'PetalWidthCm': 'Ancho del pétalo (cm)'
}

for feature in features:
    sns.displot(data=iris_df, x=feature, hue="Species", kind="hist", kde=True)
    nombre_legible = nombres_legibles[feature]
    plt.title(f"Histograma de {nombre_legible}")
    plt.show()

"""3.	Diagrama de dispersión con pares: Utiliza sns.pairplot() para crear un diagrama de dispersión que muestre la relación entre cada par de características. Agrega color a los puntos para diferenciar las especies.

Este gráfico mostrará un histograma para cada característica (sepal_length, sepal_width, petal_length, petal_width) en la diagonal, dividido por colores que representan las diferentes especies de Iris. En las otras celdas de la matriz, aparecerán diagramas de dispersión que muestran la relación entre pares de características, también diferenciados por color según la especie.
"""

sns.pairplot(iris_df, hue="Species", diag_kind="hist") #sin el diag_king hace un diagrama de linea
plt.show()

"""4.	Mapa de calor de correlación: Crea un mapa de calor que muestre la correlación entre las diferentes características del dataset.

Primero se calcula matriz de correlacción con la función corr() de pandas. Es importante indicar que seleccione solo las columnas numéricas con .select_dtypes(include=['number']) para evitar un error tipo ValueError, al intentar usar la columna de Species.
Después, con sns.heatmap() de seaborn se crea el mapa de calor.
"""

# Calcular la matriz de correlación solo para columnas numéricas
correlation_matrix = iris_df.select_dtypes(include=['number']).corr()

# Crear el mapa de calor
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("Mapa de calor de correlación")
plt.show()

"""5.	Gráfico de violín: Crea un gráfico de violín (violinplot) para cada una de las características (sepal_length, sepal_width, petal_length, petal_width), agrupado por especie.

Para crear un gráfico de violín para cada característica volvemos a recorrer las características usando la funcion violinplot()
"""

for feature in features:
    plt.figure(figsize=(8, 6))
    sns.violinplot(x="Species", y=feature, data=iris_df)
    nombre_legible = nombres_legibles[feature]
    plt.title(f"Gráfico de violín de {nombre_legible} por especie")
    plt.show()

"""Extrae conclusiones sobre el porque de los resultados obtenidos.

Histogramas:

Longitud y ancho del sépalo: Los histogramas de estas características muestran una distribución más o menos normal, con cierta superposición entre las especies. Esto sugiere que estas características por sí solas no son suficientes para separar completamente las especies.
Longitud y ancho del pétalo: Los histogramas de estas características muestran una mayor separación entre las especies, especialmente para la especie Iris-setosa, que tiene pétalos mucho más pequeños que las otras dos especies. Esto indica que estas características son más informativas para la clasificación de las especies.

Diagrama de dispersión de pares:

Relaciones entre características: El diagrama de dispersión de pares confirma las observaciones de los histogramas. Se puede ver una clara separación entre las especies en los gráficos que involucran la longitud y el ancho del pétalo.
Correlación: También se puede observar una fuerte correlación positiva entre la longitud y el ancho del pétalo, lo que indica que estas dos características tienden a aumentar o disminuir juntas.

Mapa de calor de correlación:

Confirmación de correlaciones: El mapa de calor de correlación confirma la fuerte correlación positiva entre la longitud y el ancho del pétalo. También muestra una correlación moderada entre la longitud del pétalo y la longitud del sépalo.
Selección de características: Esta información puede ser útil para la selección de características en modelos de machine learning, ya que las características altamente correlacionadas pueden proporcionar información redundante.

Gráficos de violín:

Distribución por especie: Los gráficos de violín muestran la distribución de cada característica para cada especie. Se puede observar que la especie Iris-setosa tiene una distribución más estrecha para la longitud y el ancho del pétalo, lo que indica una menor variabilidad en estas características.
Comparación de medianas: Los gráficos de violín también permiten comparar las medianas de las características entre las especies. Se puede observar que la especie Iris-virginica tiende a tener pétalos más largos y anchos que las otras dos especies.

Conclusiones generales:

Clasificación: Las características de los pétalos (longitud y ancho) son más informativas para la clasificación de las especies de Iris que las características de los sépalos.
Correlación: Existe una fuerte correlación positiva entre la longitud y el ancho del pétalo.
Variabilidad: La especie Iris-setosa tiene una menor variabilidad en las características de los pétalos que las otras dos especies.
Diferencias entre especies: La especie Iris-virginica tiende a tener pétalos más largos y anchos que las otras dos especies.
"""